### ISSUE TITLE
中国移动云空间

### ISSUE THREAD

**Issue by Angxb4cn** [HurryBy/lanzou-directlink#3]
也是一个不需要登陆就能下载的盘，支持大文件，大佬能不能支持一下
无加密：链接：https://www.ecpan.cn/web/#/yunpanProxy?path=%2F%23%2Fdrive%2Foutside&data=06630f8402ba2a14539a1c57f18d64708gasn&isShare=1

加密：链接：https://www.ecpan.cn/web/#/yunpanProxy?path=%2F%23%2Fdrive%2Foutside&data=8af109ad858523145a5d296d12698a4cWN9cgJMcur&isShare=1
访问密码：WqIKZD

**Comment by HurryBy** [comment]
刚看到信息 我放假就弄
