### ISSUE TITLE
提示密码错误

### ISSUE THREAD

**Issue by shubaofx** [HurryBy/lanzou-directlink#5]
![image](https://github.com/HurryBy/CloudDiskAnalysis/assets/46684652/2e40a543-1ec0-4d38-aa16-90374bc9e780)
完全复制你这边的代码   密码也确认没有错误 但是一直提示密码错误

**Comment by shubaofx** [comment]
这是什么问题呢

**Comment by HurryBy** [comment]
我猜你需要把lanzouk改为lanzouw

**Comment by HurryBy** [comment]
现在已经在床上了
明天我会尝试修复
顺便优化一下代码结构 稍等一下吧

**Comment by shubaofx** [comment]
好的 等你明天弄好  感谢

**Comment by HurryBy** [comment]
知道问题了 现在开始修，
